name: Dart_json_path
description: Dart json_path adapter

environment:
  sdk: '>=2.12.0-133.6.beta <3.0.0'

dependencies:
  json_path: ^0.3.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
